modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/kawaiicakes/TemplateModOneDotNineteen/issues"

[[mods]]
modId="ashliculture"
version="${file.jarVersion}"
displayName="Template Mod 1.19"
displayURL="https://github.com/kawaiicakes/TemplateModOneDotNineteen/"
logoFile="ashliculture.png"
credits="Thanks to ME!"
authors="kawaiicakes"
description='''
This is a template used for my mods so I can just copy paste this for a new 1.19.2 dev environment lol
'''

[[dependencies.ashliculture]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ashliculture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
